---

- name: Install package
  become: True
  package:
    name: kubernetes-hyperkube-kube-proxy
    state: present

- name: Configure package
  become: True
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - src: kube-proxy.j2
      dest: /etc/default/kube-proxy
    - src: systemd.service.j2
      dest: /etc/systemd/system/kube-proxy.service
  notify:
    - Reload systemd
    - Restart kube-proxy
