---

- name: Install kubernetes-node
  become: True
  package:
    name: kubernetes-node
    state: present

- name: Configure package
  become: True
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - src: kube-proxy.conf.j2
      dest: "{{ kube_proxy_config }}"
    - src: systemd.service.j2
      dest: /etc/systemd/system/kube-proxy.service
  notify:
    - Reload systemd
    - Restart kube-proxy

- name: Flush handlers
  meta: flush_handlers
